### ISSUE TITLE
Unable to change width of x-input

### ISSUE THREAD

**Issue by Centribo** [jarek-foksa/xel#64]
I have HTML code as such:
```html
<x-input skin="flat" id="search-bar" onkeydown="if(event.keyCode == 13) search()">
	<x-label>Search</x-label>
</x-input>
```
and CSS code as such:
```css
#search-bar {
	margin-right: 10px;
	width: 1000px;
}
```

But the bar is still the default size. See here:
[Image](https://puu.sh/zlc7X/7180d5ebb3.png)
